import { environment } from '../../environments/environment';

export const baseUrl: string = environment.apiUrl as string;

export namespace URL {
  export const IMAGE: string = `${baseUrl}/api/v1/users/show/image/`;
  export const RECRUITER: string = `${baseUrl}/api/v1/recruiter`;
  export const UPLOAD: string = `${baseUrl}/api/v1/upload`;
  export const SIGNIN: string = `${baseUrl}/api/v1/auth/login`;
  export const AUTH: string = `${baseUrl}/api/v1/auth`;
  export const ADMIN: string = `${baseUrl}/api/v1/admin`;
  export const USER: string = `${baseUrl}/api/v1/users`;
  export const CATEGORY: string = `${baseUrl}/api/v1/recruiter/categories`;
  export const QUALIFICATIONS: string = `${baseUrl}/api/v1/recruiter/qualifications`;
  export const JOB: string = `${baseUrl}/api/v1/recruiter/jobs`;
  export const SETTINGS: string = `${baseUrl}/api/v1/settings`;
  export const TRANSACTION: string = `${baseUrl}/api/v1/recruiter/transactions`;
  export const PAYTM: string = `${baseUrl}/api/v1/paytm`;
  export const PAYMENTS: string = `${baseUrl}/api/v1/payments`;
  export const MESSAGE: string = `${baseUrl}/api/v1/message`;
  export const SKILL: string = `${baseUrl}/api/v1/recruiter/skills`;
  export const REFRESH_TOKEN: string = `${baseUrl}/api/v1/auth/refresh-token`;
  export const CSRF_TOKEN: string = `${baseUrl}/api/v1/auth/csrf-token`;
  export const EVENTS: string = `${baseUrl}/api/v1/events`;
  export const ELASTIC_SEARCH: string = `${baseUrl}/api/v1/elastic-search`;
  export const CIRCLE: string = `${baseUrl}/api/v1/circle`;
}

export namespace constants {
  export const OTHER = '';
}

export const CURRENCIES = [
  { code: 'AED', name: 'United Arab Emirates Dirham' },
  { code: 'AFN', name: 'Afghan Afghani' },
  { code: 'ALL', name: 'Albanian Lek' },
  { code: 'AMD', name: 'Armenian Dram' },
  { code: 'ANG', name: 'Netherlands Antillean Guilder' },
  { code: 'AOA', name: 'Angolan Kwanza' },
  { code: 'ARS', name: 'Argentine Peso' },
  { code: 'AUD', name: 'Australian Dollar' },
  { code: 'AWG', name: 'Aruban Florin' },
  { code: 'AZN', name: 'Azerbaijani Manat' },
  { code: 'BAM', name: 'Bosnia-Herzegovina' },
  { code: 'BBD', name: 'Barbadian Dollar' },
  { code: 'BDT', name: 'Bangladeshi Taka' },
  { code: 'BGN', name: 'Bulgarian Lev' },
  { code: 'BHD', name: 'Bahraini Dinar' },
  { code: 'BIF', name: 'Burundian Franc' },
  { code: 'BMD', name: 'Bermudian Dollar' },
  { code: 'BND', name: 'Brunei Dollar' },
  { code: 'BOB', name: 'Bolivian Boliviano' },
  { code: 'BRL', name: 'Brazilian Real' },
  { code: 'BSD', name: 'Bahamian Dollar' },
  { code: 'BTN', name: 'Bhutanese Ngultrum' },
  { code: 'BWP', name: 'Botswana Pula' },
  { code: 'BYN', name: 'Belarusian Ruble' },
  { code: 'BZD', name: 'Belize Dollar' },
  { code: 'CAD', name: 'Canadian Dollar' },
  { code: 'CDF', name: 'Congolese Franc' },
  { code: 'CHF', name: 'Swiss Franc' },
  { code: 'CLP', name: 'Chilean Peso' },
  { code: 'CNY', name: 'Chinese Yuan' },
  { code: 'COP', name: 'Colombian Peso' },
  { code: 'CRC', name: 'Costa Rican Colón' },
  { code: 'CUP', name: 'Cuban Peso' },
  { code: 'CVE', name: 'Cape Verdean Escudo' },
  { code: 'CZK', name: 'Czech Koruna' },
  { code: 'DJF', name: 'Djiboutian Franc' },
  { code: 'DKK', name: 'Danish Krone' },
  { code: 'DOP', name: 'Dominican Peso' },
  { code: 'DZD', name: 'Algerian Dinar' },
  { code: 'EGP', name: 'Egyptian Pound' },
  { code: 'ERN', name: 'Eritrean Nakfa' },
  { code: 'ETB', name: 'Ethiopian Birr' },
  { code: 'EUR', name: 'Euro' },
  { code: 'FJD', name: 'Fijian Dollar' },
  { code: 'FKP', name: 'Falkland Islands Pound' },
  { code: 'FOK', name: 'Faroese Króna' },
  { code: 'GBP', name: 'British Pound Sterling' },
  { code: 'GEL', name: 'Georgian Lari' },
  { code: 'GGP', name: 'Guernsey Pound' },
  { code: 'GHS', name: 'Ghanaian Cedi' },
  { code: 'GIP', name: 'Gibraltar Pound' },
  { code: 'GMD', name: 'Gambian Dalasi' },
  { code: 'GNF', name: 'Guinean Franc' },
  { code: 'GTQ', name: 'Guatemalan Quetzal' },
  { code: 'GYD', name: 'Guyanaese Dollar' },
  { code: 'HKD', name: 'Hong Kong Dollar' },
  { code: 'HNL', name: 'Honduran Lempira' },
  { code: 'HRK', name: 'Croatian Kuna' },
  { code: 'HTG', name: 'Haitian Gourde' },
  { code: 'HUF', name: 'Hungarian Forint' },
  { code: 'IDR', name: 'Indonesian Rupiah' },
  { code: 'ILS', name: 'Israeli New Shekel' },
  { code: 'IMP', name: 'Manx Pound' },
  { code: 'INR', name: 'Indian Rupee' },
  { code: 'IQD', name: 'Iraqi Dinar' },
  { code: 'IRR', name: 'Iranian Rial' },
  { code: 'ISK', name: 'Icelandic Króna' },
  { code: 'JEP', name: 'Jersey Pound' },
  { code: 'JMD', name: 'Jamaican Dollar' },
  { code: 'JOD', name: 'Jordanian Dinar' },
  { code: 'JPY', name: 'Japanese Yen' },
  { code: 'KES', name: 'Kenyan Shilling' },
  { code: 'KGS', name: 'Kyrgyzstani Som' },
  { code: 'KHR', name: 'Cambodian Riel' },
  { code: 'KID', name: 'Kiribati Dollar' },
  { code: 'KMF', name: 'Comorian Franc' },
  { code: 'KRW', name: 'South Korean Won' },
  { code: 'KWD', name: 'Kuwaiti Dinar' },
  { code: 'KYD', name: 'Cayman Islands Dollar' },
  { code: 'KZT', name: 'Kazakhstani Tenge' },
  { code: 'LAK', name: 'Laotian Kip' },
  { code: 'LBP', name: 'Lebanese Pound' },
  { code: 'LKR', name: 'Sri Lankan Rupee' },
  { code: 'LRD', name: 'Liberian Dollar' },
  { code: 'LSL', name: 'Lesotho Loti' },
  { code: 'LYD', name: 'Libyan Dinar' },
  { code: 'MAD', name: 'Moroccan Dirham' },
  { code: 'MDL', name: 'Moldovan Leu' },
  { code: 'MGA', name: 'Malagasy Ariary' },
  { code: 'MKD', name: 'Macedonian Denar' },
  { code: 'MMK', name: 'Myanmar Kyat' },
  { code: 'MNT', name: 'Mongolian Tugrik' },
  { code: 'MOP', name: 'Macanese Pataca' },
  { code: 'MRU', name: 'Mauritanian Ouguiya' },
  { code: 'MUR', name: 'Mauritian Rupee' },
  { code: 'MVR', name: 'Maldivian Rufiyaa' },
  { code: 'MWK', name: 'Malawian Kwacha' },
  { code: 'MXN', name: 'Mexican Peso' },
  { code: 'MYR', name: 'Malaysian Ringgit' },
  { code: 'MZN', name: 'Mozambican Metical' },
  { code: 'NAD', name: 'Namibian Dollar' },
  { code: 'NGN', name: 'Nigerian Naira' },
  { code: 'NIO', name: 'Nicaraguan Córdoba' },
  { code: 'NOK', name: 'Norwegian Krone' },
  { code: 'NPR', name: 'Nepalese Rupee' },
  { code: 'NZD', name: 'New Zealand Dollar' },
  { code: 'OMR', name: 'Omani Rial' },
  { code: 'PAB', name: 'Panamanian Balboa' },
  { code: 'PEN', name: 'Peruvian Nuevo Sol' },
  { code: 'PGK', name: 'Papua New Guinean Kina' },
  { code: 'PHP', name: 'Philippine Peso' },
  { code: 'PKR', name: 'Pakistani Rupee' },
  { code: 'PLN', name: 'Polish Zloty' },
  { code: 'PYG', name: 'Paraguayan Guarani' },
  { code: 'QAR', name: 'Qatari Rial' },
  { code: 'RON', name: 'Romanian Leu' },
  { code: 'RSD', name: 'Serbian Dinar' },
  { code: 'RUB', name: 'Russian Ruble' },
  { code: 'RWF', name: 'Rwandan Franc' },
  { code: 'SAR', name: 'Saudi Riyal' },
  { code: 'SBD', name: 'Solomon Islands Dollar' },
  { code: 'SCR', name: 'Seychellois Rupee' },
  { code: 'SDG', name: 'Sudanese Pound' },
  { code: 'SEK', name: 'Swedish Krona' },
  { code: 'SGD', name: 'Singapore Dollar' },
  { code: 'SHP', name: 'Saint Helena Pound' },
  { code: 'SLL', name: 'Sierra Leonean Leone' },
  { code: 'SOS', name: 'Somali Shilling' },
  { code: 'SRD', name: 'Surinamese Dollar' },
  { code: 'SSP', name: 'South Sudanese Pound' },
  { code: 'STN', name: 'São Tomé and Príncipe Dobra' },
  { code: 'SYP', name: 'Syrian Pound' },
  { code: 'SZL', name: 'Swazi Lilangeni' },
  { code: 'THB', name: 'Thai Baht' },
  { code: 'TJS', name: 'Tajikistani Somoni' },
  { code: 'TMT', name: 'Turkmenistani Manat' },
  { code: 'TND', name: 'Tunisian Dinar' },
  { code: 'TOP', name: 'Tongan Paʻanga' },
  { code: 'TRY', name: 'Turkish Lira' },
  { code: 'TTD', name: 'Trinidad and Tobago Dollar' },
  { code: 'TVD', name: 'Tuvaluan Dollar' },
  { code: 'TWD', name: 'New Taiwan Dollar' },
  { code: 'TZS', name: 'Tanzanian Shilling' },
  { code: 'UAH', name: 'Ukrainian Hryvnia' },
  { code: 'UGX', name: 'Ugandan Shilling' },
  { code: 'USD', name: 'United States Dollar' },
  { code: 'UYU', name: 'Uruguayan Peso' },
  { code: 'UZS', name: 'Uzbekistan Som' },
  { code: 'VES', name: 'Venezuelan Bolívar Soberano' },
  { code: 'VND', name: 'Vietnamese Dong' },
  { code: 'VUV', name: 'Vanuatu Vatu' },
  { code: 'WST', name: 'Samoan Tala' },
  { code: 'XAF', name: 'CFA Franc BEAC' },
  { code: 'XCD', name: 'East Caribbean Dollar' },
  { code: 'XDR', name: 'Special Drawing Rights' },
  { code: 'XOF', name: 'CFA Franc BCEAO' },
  { code: 'XPF', name: 'CFP Franc' },
  { code: 'YER', name: 'Yemeni Rial' },
  { code: 'ZAR', name: 'South African Rand' },
  { code: 'ZMW', name: 'Zambian Kwacha' },
  { code: 'ZWL', name: 'Zimbabwean Dollar' },
];

export const COUNTRIES = [
  { code: '(+93) AF', name: 'Afghanistan' },
  { code: '(+355) AL', name: 'Albania' },
  { code: '(+213) DZ', name: 'Algeria' },
  { code: '(+376) AD', name: 'Andorra' },
  { code: '(+244) AO', name: 'Angola' },
  { code: '(+1) AI', name: 'Anguilla' },
  { code: '(+1) AG', name: 'Antigua and Barbuda' },
  { code: '(+54) AR', name: 'Argentina' },
  { code: '(+374) AM', name: 'Armenia' },
  { code: '(+297) AW', name: 'Aruba' },
  { code: '(+61) AU', name: 'Australia' },
  { code: '(+43) AT', name: 'Austria' },
  { code: '(+994) AZ', name: 'Azerbaijan' },
  { code: '(+1) BS', name: 'Bahamas' },
  { code: '(+973) BH', name: 'Bahrain' },
  { code: '(+880) BD', name: 'Bangladesh' },
  { code: '(+1) BB', name: 'Barbados' },
  { code: '(+375) BY', name: 'Belarus' },
  { code: '(+32) BE', name: 'Belgium' },
  { code: '(+501) BZ', name: 'Belize' },
  { code: '(+229) BJ', name: 'Benin' },
  { code: '(+1) BM', name: 'Bermuda' },
  { code: '(+975) BT', name: 'Bhutan' },
  { code: '(+591) BO', name: 'Bolivia' },
  { code: '(+387) BA', name: 'Bosnia and Herzegovina' },
  { code: '(+267) BW', name: 'Botswana' },
  { code: '(+55) BR', name: 'Brazil' },
  { code: '(+246) IO', name: 'British Indian Ocean Territory' },
  { code: '(+1) VG', name: 'British Virgin Islands' },
  { code: '(+673) BN', name: 'Brunei' },
  { code: '(+359) BG', name: 'Bulgaria' },
  { code: '(+226) BF', name: 'Burkina Faso' },
  { code: '(+257) BI', name: 'Burundi' },
  { code: '(+855) KH', name: 'Cambodia' },
  { code: '(+237) CM', name: 'Cameroon' },
  { code: '(+1) CA', name: 'Canada' },
  { code: '(+238) CV', name: 'Cape Verde' },
  { code: '(+1) KY', name: 'Cayman Islands' },
  { code: '(+236) CF', name: 'Central African Republic' },
  { code: '(+61) CC', name: 'Christmas Island' },
  { code: '(+61) CK', name: 'Cook Islands' },
  { code: '(+57) CO', name: 'Colombia' },
  { code: '(+506) CR', name: 'Costa Rica' },
  { code: '(+225) CI', name: "Côte d'Ivoire" },
  { code: '(+385) HR', name: 'Croatia' },
  { code: '(+53) CU', name: 'Cuba' },
  { code: '(+599) CW', name: 'Curaçao' },
  { code: '(+357) CY', name: 'Cyprus' },
  { code: '(+420) CZ', name: 'Czech Republic' },
  { code: '(+45) DK', name: 'Denmark' },
  { code: '(+253) DJ', name: 'Djibouti' },
  { code: '(+1) DM', name: 'Dominica' },
  { code: '(+1) DO', name: 'Dominican Republic' },
  { code: '(+593) EC', name: 'Ecuador' },
  { code: '(+20) EG', name: 'Egypt' },
  { code: '(+503) SV', name: 'El Salvador' },
  { code: '(+1) GQ', name: 'Equatorial Guinea' },
  { code: '(+291) ER', name: 'Eritrea' },
  { code: '(+372) EE', name: 'Estonia' },
  { code: '(+251) ET', name: 'Ethiopia' },
  { code: '(+500) FK', name: 'Falkland Islands' },
  { code: '(+1) FM', name: 'Federated States of Micronesia' },
  { code: '(+679) FJ', name: 'Fiji' },
  { code: '(+358) FI', name: 'Finland' },
  { code: '(+33) FR', name: 'France' },
  { code: '(+241) GA', name: 'Gabon' },
  { code: '(+220) GM', name: 'Gambia' },
  { code: '(+995) GE', name: 'Georgia' },
  { code: '(+49) DE', name: 'Germany' },
  { code: '(+233) GH', name: 'Ghana' },
  { code: '(+350) GI', name: 'Gibraltar' },
  { code: '(+30) GR', name: 'Greece' },
  { code: '(+299) GL', name: 'Greenland' },
  { code: '(+1) GD', name: 'Grenada' },
  { code: '(+590) GP', name: 'Guadeloupe' },
  { code: '(+1) GU', name: 'Guam' },
  { code: '(+502) GT', name: 'Guatemala' },
  { code: '(+224) GN', name: 'Guinea' },
  { code: '(+245) GW', name: 'Guinea-Bissau' },
  { code: '(+595) GY', name: 'Guyana' },
  { code: '(+509) HT', name: 'Haiti' },
  { code: '(+504) HN', name: 'Honduras' },
  { code: '(+36) HU', name: 'Hungary' },
  { code: '(+354) IS', name: 'Iceland' },
  { code: '(+91) IN', name: 'India' },
  { code: '(+62) ID', name: 'Indonesia' },
  { code: '(+964) IQ', name: 'Iraq' },
  { code: '(+353) IE', name: 'Ireland' },
  { code: '(+972) IL', name: 'Israel' },
  { code: '(+39) IT', name: 'Italy' },
  { code: '(+1) JM', name: 'Jamaica' },
  { code: '(+81) JP', name: 'Japan' },
  { code: '(+44) JE', name: 'Jersey' },
  { code: '(+962) JO', name: 'Jordan' },
  { code: '(+7) KZ', name: 'Kazakhstan' },
  { code: '(+254) KE', name: 'Kenya' },
  { code: '(+686) KI', name: 'Kiribati' },
  { code: '(+965) KW', name: 'Kuwait' },
  { code: '(+996) KG', name: 'Kyrgyzstan' },
  { code: '(+856) LA', name: 'Laos' },
  { code: '(+371) LV', name: 'Latvia' },
  { code: '(+961) LB', name: 'Lebanon' },
  { code: '(+266) LS', name: 'Lesotho' },
  { code: '(+231) LR', name: 'Liberia' },
  { code: '(+218) LY', name: 'Libya' },
  { code: '(+423) LI', name: 'Liechtenstein' },
  { code: '(+370) LT', name: 'Lithuania' },
  { code: '(+352) LU', name: 'Luxembourg' },
  { code: '(+261) MG', name: 'Madagascar' },
  { code: '(+265) MW', name: 'Malawi' },
  { code: '(+60) MY', name: 'Malaysia' },
  { code: '(+960) MV', name: 'Maldives' },
  { code: '(+223) ML', name: 'Mali' },
  { code: '(+356) MT', name: 'Malta' },
  { code: '(+692) MH', name: 'Marshall Islands' },
  { code: '(+596) MQ', name: 'Martinique' },
  { code: '(+222) MR', name: 'Mauritania' },
  { code: '(+230) MU', name: 'Mauritius' },
  { code: '(+262) RE', name: 'Réunion' },
  { code: '(+52) MX', name: 'Mexico' },
  { code: '(+691) FM', name: 'Micronesia' },
  { code: '(+373) MD', name: 'Moldova' },
  { code: '(+377) MC', name: 'Monaco' },
  { code: '(+976) MN', name: 'Mongolia' },
  { code: '(+382) ME', name: 'Montenegro' },
  { code: '(+1) MS', name: 'Montserrat' },
  { code: '(+212) MA', name: 'Morocco' },
  { code: '(+258) MZ', name: 'Mozambique' },
  { code: '(+95) MM', name: 'Myanmar' },
  { code: '(+264) NA', name: 'Namibia' },
  { code: '(+674) NR', name: 'Nauru' },
  { code: '(+977) NP', name: 'Nepal' },
  { code: '(+31) NL', name: 'Netherlands' },
  { code: '(+599) AN', name: 'Netherlands Antilles' },
  { code: '(+687) NC', name: 'New Caledonia' },
  { code: '(+64) NZ', name: 'New Zealand' },
  { code: '(+505) NI', name: 'Nicaragua' },
  { code: '(+227) NE', name: 'Niger' },
  { code: '(+234) NG', name: 'Nigeria' },
  { code: '(+683) NU', name: 'Niue' },
  { code: '(+672) NF', name: 'Norfolk Island' },
  { code: '(+1) MP', name: 'Northern Mariana Islands' },
  { code: '(+47) NO', name: 'Norway' },
  { code: '(+968) OM', name: 'Oman' },
  { code: '(+92) PK', name: 'Pakistan' },
  { code: '(+680) PW', name: 'Palau' },
  { code: '(+970) PS', name: 'Palestine' },
  { code: '(+507) PA', name: 'Panama' },
  { code: '(+675) PG', name: 'Papua New Guinea' },
  { code: '(+595) PY', name: 'Paraguay' },
  { code: '(+51) PE', name: 'Peru' },
  { code: '(+63) PH', name: 'Philippines' },
  { code: '(+48) PL', name: 'Poland' },
  { code: '(+351) PT', name: 'Portugal' },
  { code: '(+1) PR', name: 'Puerto Rico' },
  { code: '(+974) QA', name: 'Qatar' },
  { code: '(+262) RE', name: 'Réunion' },
  { code: '(+40) RO', name: 'Romania' },
  { code: '(+7) RU', name: 'Russia' },
  { code: '(+250) RW', name: 'Rwanda' },
  { code: '(+590) BL', name: 'Saint Barthélemy' },
  { code: '(+1) KN', name: 'Saint Kitts and Nevis' },
  { code: '(+1) LC', name: 'Saint Lucia' },
  { code: '(+590) MF', name: 'Saint Martin' },
  { code: '(+1) SX', name: 'Sint Maarten' },
  { code: '(+1) VC', name: 'Saint Vincent and the Grenadines' },
  { code: '(+685) WS', name: 'Samoa' },
  { code: '(+378) SM', name: 'San Marino' },
  { code: '(+239) ST', name: 'Sao Tome and Principe' },
  { code: '(+966) SA', name: 'Saudi Arabia' },
  { code: '(+221) SN', name: 'Senegal' },
  { code: '(+381) RS', name: 'Serbia' },
  { code: '(+248) SC', name: 'Seychelles' },
  { code: '(+232) SL', name: 'Sierra Leone' },
  { code: '(+65) SG', name: 'Singapore' },
  { code: '(+421) SK', name: 'Slovakia' },
  { code: '(+386) SI', name: 'Slovenia' },
  { code: '(+677) SB', name: 'Solomon Islands' },
  { code: '(+252) SO', name: 'Somalia' },
  { code: '(+27) ZA', name: 'South Africa' },
  { code: '(+82) KR', name: 'South Korea' },
  { code: '(+211) SS', name: 'South Sudan' },
  { code: '(+34) ES', name: 'Spain' },
  { code: '(+94) LK', name: 'Sri Lanka' },
  { code: '(+249) SD', name: 'Sudan' },
  { code: '(+597) SR', name: 'Suriname' },
  { code: '(+268) SZ', name: 'Swaziland' },
  { code: '(+46) SE', name: 'Sweden' },
  { code: '(+41) CH', name: 'Switzerland' },
  { code: '(+963) SY', name: 'Syria' },
  { code: '(+886) TW', name: 'Taiwan' },
  { code: '(+992) TJ', name: 'Tajikistan' },
  { code: '(+255) TZ', name: 'Tanzania' },
  { code: '(+66) TH', name: 'Thailand' },
  { code: '(+670) TL', name: 'Timor-Leste' },
  { code: '(+228) TG', name: 'Togo' },
  { code: '(+690) TK', name: 'Tokelau' },
  { code: '(+676) TO', name: 'Tonga' },
  { code: '(+1) TT', name: 'Trinidad and Tobago' },
  { code: '(+216) TN', name: 'Tunisia' },
  { code: '(+90) TR', name: 'Turkey' },
  { code: '(+993) TM', name: 'Turkmenistan' },
  { code: '(+1) TC', name: 'Turks and Caicos Islands' },
  { code: '(+688) TV', name: 'Tuvalu' },
  { code: '(+256) UG', name: 'Uganda' },
  { code: '(+380) UA', name: 'Ukraine' },
  { code: '(+971) AE', name: 'United Arab Emirates' },
  { code: '(+44) GB', name: 'United Kingdom' },
  { code: '(+1) US', name: 'United States' },
  { code: '(+598) UY', name: 'Uruguay' },
  { code: '(+998) UZ', name: 'Uzbekistan' },
  { code: '(+678) VU', name: 'Vanuatu' },
  { code: '(+379) VA', name: 'Vatican City' },
  { code: '(+58) VE', name: 'Venezuela' },
  { code: '(+84) VN', name: 'Vietnam' },
  { code: '(+1284) VG', name: 'British Virgin Islands' },
  { code: '(+1340) VI', name: 'United States Virgin Islands' },
  { code: '(+681) WF', name: 'Wallis and Futuna' },
  { code: '(+967) YE', name: 'Yemen' },
  { code: '(+260) ZM', name: 'Zambia' },
  { code: '(+263) ZW', name: 'Zimbabwe' },
];
